package day26_Exceptions2;

public class test9 {
    //    void Div() throws ArithmeticException {
//        int a = 25, b = 0, rs;
//        rs = a / b;
//        System.out.print("\n\tThe result is : " + rs);
//    }
//
//    public
//    static void main(String[] args) {
//        Test2 t = new Test2();
//        try {
//            t.Div();
//        } catch (ArithmeticException e) {
//            System.out.print("\n\tError : " + e.getMessage());
//        }
//        System.out.print("\n\tBYE TECHNO");
//    }
//}
////Options:
////1. BYE TECHNO
////2. Compile time error
////3. Error: / by zero
////4. Error : / by zero
////BYE TECHNO
}
